---
- name: Check homebrew existance
  command: which brew
  changed_when: false
  failed_when: false
  register: homebrew_status


- name: Install homebrew
  shell: |
    /usr/bin/ruby -e \
    "$(curl -fsSL \
      https://raw.githubusercontent.com/Homebrew/install/master/install \
    )"
  when: homebrew_status is failed
