---
- name: Install packages to allow apt to use a repository over HTTPS
  shell: |
    apt-get update \
    && apt-get install -y \
    apt-transport-https \
    ca-certificates \
    software-properties-common

- name: Install http client packages
  package:
    name:
      - wget
      - curl
    state: present
