---
- name: Install packages to allow apt to use a repository over HTTPS
  shell: |
    apt-get update \
    && apt-get install -y \
    apt-transport-https \
    ca-certificates \
    software-properties-common

- name: Update apt-get
  shell: apt-get update

- name: Install curl
  shell: apt-get install -y curl

- name: Install wget
  shell: apt-get install -y wget
