---
language: python
python: "2.7"
sudo: required
os:
  - ubuntu
install:
  - pip install ansible
services:
  - docker
jobs:
  include:
    - stage: test
      name: Test other distros
      script: ./tests/test.sh
