---
language: python
python: "2.7"
sudo: required
os:
  - ubuntu
install:
  - pip install ansible
services:
  - docker
jobs:
  include:
    - stage: deploy
      name: Deploy on Mac OS X
      script: ./setup.sh

    - stage: test
      name: Test other distros
      script: ./tests/test.sh
