language: python
python: "2.7"
sudo: required
os:
- ubuntu
install:
- pip install ansible
services:
- docker
jobs:
  include:
  - stage: tests
    name: Deploy on ubuntu docker container
    script: ./tests/test_on_ubuntu_container.sh
  - stage: deploy
    name: Deploy on localhost
    script: ./tests/test_on_localhost.sh
