---
- name: Set alacritty color scheme
  set_fact:
    alacritty_color_scheme: "{{ alacritty_gruvbox_dark_scheme }}"

- name: Upload alacritty configuration file
  template:
    src: alacritty.yml.j2
    dest: ~/.config/alacritty/alacritty.yml
