---
- name: Prepare alacritty config directory
  file:
    path: "{{ alacritty_config_path | dirname }}"
    state: directory

- name: Set alacritty color scheme
  set_fact:
    alacritty_color_scheme: "{{ alacritty_gruvbox_dark_scheme }}"

- name: Upload alacritty configuration file
  template:
    src: alacritty.yml.j2
    dest: "{{ alacritty_config_path }}"
