---
- name: Create alacritty directory
  file:
    path: ~/.config/alacritty
    state: directory

- name: Upload alacritty config file
  copy:
    src: alacritty.yaml
    dest: ~/.config/alacritty/alacritty.yaml

