---
- name: Install packages
  package:
    name:
      - bat
      - bpython
      - git-flow
      - pgcli
      - fzf
      - mongocli
      - cowsay
      - grep
      - jq
      - kcat
      - kubectx
      - thefuck
      - tree
      - vegeta
      - yq
      - gh
      - neovim
      - fzf
      - ca-certificates
      - cjson
      - netcat
      - net-tools
    state: present

- name: Configure fzf
  command: /usr/local/opt/fzf/install
