---
- name: Install packages
  package:
    state: present
    name:
      - bat
      - bpython
      - git-flow
      - pgcli
      - fzf
      - mongocli
      - cowsay
      - grep
      - jq
      - kcat
      - kubectx
      - thefuck
      - tree
      - vegeta
      - yq
      - gh
      - neovim
      - fzf
      - ca-certificates
      - cjson
      - netcat
      - k9s
