---
- name: Install packages
  package:
    name:
      - bat
      - bpython
      - git-flow
      - pgcli
      - fzf
    state: present

- name: Configure fzf
  command: /usr/local/opt/fzf/install
