---
- name: Set OS X VS Code Path
  set_fact:
    vs_code_path: ~/Library/Application Support/Code
  when: ansible_distribution == 'MacOSX'

- name: Create VS Code Path
  file:
    path: "{{ vs_code_path }}/User"
    state: directory

- name: Upload settings.json file
  copy:
    src: settings.json
    dest: "{{ vs_code_path }}/settings.json"
