---
- name: Check if gotop is installed
  command: which gotop
  ignore_errors: true
  register: gotop_installed

- name: Install gotop
  when: gotop_installed is failed
  block:
    - name: Clone gotop toolkit
      command: git clone --depth 1 https://github.com/cjbassi/gotop /tmp/gotop
    - name: Download gotop
      command: /tmp/gotop/scripts/download.sh
    - name: Add gotop to path
      command: mv gotop /usr/local/bin
