---
- name: Install vim
  package:
    name: nvim
    state: present

- name: Upload .vimrc config file
  copy:
    src: init.vim
    dest: ~/.config/nvim

- name: Install plugins
  shell: nvim +'PlugInstall --sync' +qa

- name: Install vim Plug
  shell: |
    sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
           https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
