---
- name: Install tmux on Mac OS X
  when: ansible_distribution == 'MacOSX'
  homebrew:
    name: tmux
    state: present

- name: Install tmux on Ubuntu
  when: ansible_distribution == 'Ubuntu'
  apt:
    name: tmux
    state: present

- name: Install tmux on Alpine Linux
  when: ansible_distribution == 'Alpine'
  apk:
    name: tmux
    state: present

- name: Upload tmux config file
  copy:
    src: .tmux.conf
    dest: ~/.tmux.conf
