---
- name: Install fish
  package:
    name: fish
    state: present

- name: Add fish to shells
  become: true
  lineinfile:
    path: /etc/shells
    line: /usr/local/bin/fish

- name: Set fish as default shell
  become: true
  command: chsh -s /usr/local/bin/fish

- name: Create fish configuration directory
  file:
    path: "{{ fish_config_directory }}"
    state: directory

- name: Upload fish configuration
  copy:
    src: "{{ item }}"
    dest: "{{ fish_config_directory }}/{{ item }}"
  with_items:
    - config.fish
    - functions/
    - fish_variables
    - README.md
