---
- name: Install fish on Mac OS X
  when: ansible_distribution == 'MacOSX'
  homebrew:
    name: fish
    state: present

- name: Install fish on Ubuntu
  when: ansible_distribution == 'Ubuntu'
  apt:
    name: fish
    state: present

- name: Install fish on Alpine Linux
  when: ansible_distribution == 'Alpine'
  apk:
    name: fish
    state: present

- name: Create fish configuration directory
  file:
    path: "{{ fish_config_directory }}"
    state: directory

- name: Upload fish configuration
  copy:
    src: "{{ item }}"
    dest: "{{ fish_config_directory }}/{{ item }}"
  with_items:
    - config.fish
    - functions/
    - fish_variables
    - README.md
