---
- name: Install git
  package:
    name: git
    state: present

- name: Configure git
  template:
    src: .gitconfig.j2
    dest: ~/.gitconfig

- name: Copy ~/.gitignore
  file:
    src: .gitignore
    dest: ~/.gitignore
  ignore_errors: true
