---
- name: Check if fzf is installed
  command: which fzf
  register: fzf_status
  changed_when: false
  ignore_errors: true

- name: Install fzf
  when: fzf_status is failed
  shell: |
    git clone --depth 1 https://github.com/junegunn/fzf.git {{ fzf_home }} \
    && {{ fzf_home }}/install {{ fzf_install_args | join(" ") }}
