---
- include: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
- include: macosx.yml
  when: ansible_distribution == 'MacOSX'
- include: alpine.yml
  when: ansible_distribution == 'Alpine'
- include: install_packages.yml
- include: install_themes.yml
