---

- name: Install Docker on Mac OS X
  when: ansible_distribution == 'MacOSX'
  homebrew:
    name: docker
    state: present

- include: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: Install Docker on Alpine Linux
  when: ansible_distribution == 'Alpine'
  apk:
    name: docker
    state: present
