---
- name: Add Docker’s official GPG key
  shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - \
- name: Set up the stable repository
  shell: |
    add-apt-repository \
    "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) \
    stable"
- name: Install Docker CE
  shell: |
    apt-get update \
    && apt-get install -y docker-ce
