---
- name: Install docker on Ubuntu
  when: docker_status is failed
  become: true
  block:
    - name: Add Docker’s official GPG key
      shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

    - name: Verify the key with the fingerprint
      command: apt-key fingerprint 0EBFCD88

    - name: Add `apt` repository
      shell: |
        add-apt-repository \
        "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
        $(lsb_release -cs) stable"

    - name: Install Docker CE
      shell: |
        apt-get update \
        && apt-get install docker-ce docker-ce-cli containerd.io
