---
- name: Setup developers environment
  hosts: localhost
  connection: local
  roles:
    - role: home
      tags:
        - core
    - role: core
      tags:
        - core
    - role: git
      tags:
        - git
        - core
        - ide
    - role: vim
      tags:
        - vim
        - editor
        - ide
    - role: tmux
      tags:
        - tmux
    - role: fish
      tags:
        - fish
        - shell
    - role: packages
      tags:
        - bat
        - git-flow
        - bpython
        - fzf
        - ide
