---
- name: Configure development environment
  hosts: localhost
  connection: local
  roles:
    - role: home
      tags:
        - core
    - role: core
      tags:
        - core
    - role: nvim
      tags:
        - nvim
        - vim
        - editor
        - ide
    - role: packages
      tags:
        - bat
        - bpython
        - git-flow
        - pgcli
        - fzf
        - mongocli
        - cowsay
        - grep
        - jq
        - kcat
        - kubectx
        - redis-cli
        - thefuck
        - tree
        - vegeta
        - yq
        - ide
        - gh
    - role: code
      tags:
        - code
        - ide
