---
- name: Configure development environment
  hosts: localhost
  connection: local
  roles:
    - role: home
      tags:
        - core
    - role: core
      tags:
        - core
    - role: git
      tags:
        - git
        - core
        - ide
    - role: nvim
      tags:
        - nvim
        - vim
        - editor
        - ide
    - role: alacritty
      tags:
        - alacritty
        - terminal
    - role: tmux
      tags:
        - tmux
#    - role: fish
#      tags:
#        - fish
#        - shell
    - role: packages
      tags:
        - bat
        - bpython
        - git-flow
        - pgcli
        - fzf
        - mongocli
        - cowsay
        - grep
        - jq
        - kcat
        - kubectx
        - redis-cli
        - thefuck
        - tree
        - vegeta
        - yq
        - ide
        - gh
    - role: zsh
      tags:
        - ide
        - zsh
    - role: code
      tags:
        - code
        - ide
